export const seedData = {
  siteSettings: {
    name: 'Iyaz Ibrahim',
    roleLine: 'System Engineer — infrastructure, networks, and the platforms behind them',
    tagline: 'I keep five Penang sites online — and build the platforms behind them.',
    supportingStatement:
      'I run multi-site ICT and network operations, deploy internal platforms, and turn requirements into reliable systems.',
    valueProposition:
      'Stable infrastructure at every location. Practical security. Platforms that ship.',
    availability: 'Open to infrastructure, cloud, and DevOps roles.',
    profileSummary:
      'System engineer across multi-site ICT, Microsoft 365, self-hosted platforms, and internal app development — ops by day, DevOps when it counts.',
    aboutParagraphs: [
      {
        text: "I run ICT and network operations for Digital Penang's main office and four digital library sites across Penang. Stable networks, documented assets, and security that doesn't get in the way.",
      },
      {
        text: 'On the ground I install, troubleshoot, and coordinate with vendors. I also build internal apps, run CI/CD on self-hosted runners, and deploy with Docker — with Zabbix watching so small issues never become outages.',
      },
    ],
    currentlyExploring: [
      { text: 'Zabbix across library sites' },
      { text: 'Infrastructure automation' },
      { text: 'Internal platform development' },
      { text: 'Infrastructure planning & execution' },
    ],
    locations: [
      {
        name: 'Digital Penang Main Office',
        type: 'Office',
        lat: 5.4164,
        lng: 100.3327,
        mapX: 48,
        mapY: 42,
      },
      {
        name: 'PDL Phase 1',
        type: '135, Jln Masjid Negeri, Taman Guan Joo Seng, 11600 George Town',
        lat: 5.4049527,
        lng: 100.3039317,
        mapX: 46,
        mapY: 50,
      },
      {
        name: 'PDL Phase 2',
        type: '123, Jln Masjid Negeri, Taman Guan Joo Seng, 11600 George Town',
        lat: 5.4057053,
        lng: 100.3038011,
        mapX: 48,
        mapY: 48,
      },
      {
        name: 'Butterworth Digital Library',
        type: 'Library site',
        lat: 5.3991,
        lng: 100.3638,
        mapX: 58,
        mapY: 28,
      },
      {
        name: 'Batu Maung Digital Library',
        type: 'Library site',
        lat: 5.2852,
        lng: 100.2901,
        mapX: 40,
        mapY: 72,
      },
    ],
    email: 'iyazbrhm@gmail.com',
    phone: '0197644874',
    linkedin: 'https://www.linkedin.com/in/iyazibrahim',
    github: 'https://github.com/iyazibrahim',
    location: 'Penang, Malaysia',
    seoTitle: 'Iyaz Ibrahim | System Engineer',
    seoDescription:
      'System Engineer in Penang — multi-site ICT, networking, Microsoft 365, Zabbix, and internal platforms.',
    principles: [
      {
        title: 'Reliability first',
        description: 'Stable, documented, monitored, recoverable.',
      },
      {
        title: 'Practical security',
        description: 'Reduce risk without blocking the work.',
      },
      {
        title: 'Automate the repeat work',
        description: 'Less manual effort, fewer mistakes.',
      },
    ],
    stackCategories: [
      {
        category: 'Networking',
        items: [
          { name: 'Cisco' },
          { name: 'Fortinet' },
          { name: 'Extreme Networks' },
          { name: 'Ubiquiti' },
          { name: 'VLAN' },
          { name: 'SNMP' },
        ],
      },
      {
        category: 'Microsoft 365',
        items: [
          { name: 'User onboarding' },
          { name: 'Account provisioning' },
          { name: 'Entra ID' },
          { name: 'Exchange Online' },
          { name: 'SharePoint permissions' },
          { name: 'Licensing' },
          { name: 'MFA' },
        ],
      },
      {
        category: 'Cloud',
        items: [
          { name: 'Azure' },
          { name: 'Cloudflare' },
          { name: 'Linux VPS' },
          { name: 'Docker' },
        ],
      },
      {
        category: 'Security',
        items: [
          { name: 'Access management' },
          { name: 'MFA' },
          { name: 'Vulnerability assessment' },
          { name: 'Network segmentation' },
        ],
      },
      {
        category: 'DevOps',
        items: [
          { name: 'GitHub Actions' },
          { name: 'CI/CD' },
          { name: 'Dokploy' },
          { name: 'Staging environments' },
        ],
      },
      {
        category: 'Monitoring',
        items: [
          { name: 'Zabbix' },
          { name: 'Website monitoring' },
          { name: 'Office infrastructure monitoring' },
          { name: 'Multi-site monitoring (planned)' },
        ],
      },
      {
        category: 'Development',
        items: [
          { name: 'React' },
          { name: 'Flask' },
          { name: 'Node.js' },
          { name: 'Laravel' },
          { name: 'Python' },
        ],
      },
      {
        category: 'Servers and operating systems',
        items: [
          { name: 'Windows Server' },
          { name: 'Linux' },
          { name: 'IIS' },
          { name: 'VMware' },
        ],
      },
    ],
  },
  metrics: [
    {
      label: 'Locations Supported',
      value: '5',
      description: 'Main office + four library sites',
      sort: 1,
    },
    {
      label: 'Applications Deployed',
      value: '5',
      description: 'Internal apps and workflows',
      sort: 2,
    },
    {
      label: 'ICT Assets Documented',
      value: '~100',
      description: 'Across all managed sites',
      sort: 3,
    },
    {
      label: 'Migration Downtime',
      value: '15 min',
      description: 'Library internet cutover',
      sort: 4,
    },
  ],
  capabilities: [
    {
      group: 'infrastructure',
      sort: 1,
      items: [
        { name: 'Multi-site ICT operations' },
        { name: 'Network design' },
        { name: 'Switching and VLANs' },
        { name: 'Wi-Fi deployment' },
        { name: 'CCTV' },
        { name: 'Firewall and router planning' },
        { name: 'Internet migration' },
        { name: 'Asset documentation' },
      ],
    },
    {
      group: 'devops',
      sort: 2,
      items: [
        { name: 'GitHub Actions' },
        { name: 'CI/CD' },
        { name: 'Zabbix deployment' },
        { name: 'Website monitoring' },
        { name: 'Office infra monitoring' },
        { name: 'Staging environments' },
        { name: 'Cloud backups' },
      ],
    },
    {
      group: 'cloud',
      sort: 3,
      items: [
        { name: 'Microsoft 365 administration' },
        { name: 'User onboarding' },
        { name: 'Account provisioning' },
        { name: 'Microsoft Entra ID' },
        { name: 'Email and licensing' },
        { name: 'Azure administration' },
        { name: 'Linux' },
        { name: 'VPS' },
        { name: 'Cloudflare' },
        { name: 'Docker' },
        { name: 'Dokploy' },
      ],
    },
    {
      group: 'security',
      sort: 4,
      items: [
        { name: 'Access management' },
        { name: 'MFA' },
        { name: 'Vulnerability assessment' },
        { name: 'Website security' },
        { name: 'Network segmentation' },
        { name: 'Security administration' },
      ],
    },
    {
      group: 'development',
      sort: 5,
      items: [
        { name: 'React' },
        { name: 'Flask' },
        { name: 'Node.js' },
        { name: 'Laravel' },
        { name: 'Python' },
        { name: 'MQTT' },
        { name: 'MySQL' },
      ],
    },
  ],
  experience: [
    {
      title: 'System Engineer',
      company: 'Digital Penang',
      location: 'Penang, Malaysia',
      startDate: 'March 2026',
      endDate: 'Present',
      sort: 1,
      bullets: [
        { text: 'ICT and network ops across main office and four library sites.' },
        { text: 'Install, troubleshoot, and document ~100 devices per site.' },
        { text: 'Coordinate vendors and site leads on security and decisions.' },
        { text: 'Zabbix monitoring for web and office — libraries next.' },
        { text: 'Build apps with React, Docker, GitHub Actions, Cloudflare.' },
        { text: 'Microsoft 365, Entra ID, Azure — onboarding and licensing.' },
        { text: 'Library internet migration: 15 minutes downtime.' },
        { text: 'Five internal apps on self-hosted Docker and Dokploy.' },
      ],
      techTags: [
        { tag: 'Fortinet' },
        { tag: 'Cisco' },
        { tag: 'Microsoft 365' },
        { tag: 'Azure' },
        { tag: 'Docker' },
        { tag: 'Zabbix' },
        { tag: 'Dokploy' },
      ],
    },
    {
      title: 'IT Support and Junior Systems Intern',
      company: 'SCHOTT Glass Sdn Bhd',
      location: 'Kulim, Malaysia',
      startDate: 'September 2025',
      endDate: 'December 2025',
      sort: 2,
      bullets: [
        { text: 'IT support across office, production, and cleanrooms.' },
        { text: 'Asset lifecycle and workstation deployment.' },
        { text: 'Infrastructure checks, AP verification, vendor coordination.' },
        { text: 'Built machine monitoring platform — Laravel, Python, MQTT.' },
        { text: 'Deployed on Windows Server with IIS.' },
      ],
      techTags: [
        { tag: 'Laravel' },
        { tag: 'Python' },
        { tag: 'MQTT' },
        { tag: 'MySQL' },
        { tag: 'Windows Server' },
        { tag: 'IIS' },
      ],
    },
    {
      title: 'Network Infrastructure Intern',
      company: 'V-Network Sdn Bhd',
      location: 'Malaysia',
      startDate: 'March 2023',
      endDate: 'September 2023',
      sort: 3,
      bullets: [
        { text: 'Network projects for SME and government clients.' },
        { text: 'Cisco and Extreme Networks config and troubleshooting.' },
        { text: 'Site surveys, wireless planning, technical documentation.' },
        { text: 'Network troubleshooting and security assessments.' },
      ],
      techTags: [
        { tag: 'Cisco' },
        { tag: 'Extreme Networks' },
        { tag: 'VLAN' },
        { tag: 'Wireless planning' },
      ],
    },
    {
      title: 'Freelance IT Support Technician',
      company: 'Self-Employed',
      location: 'Penang, Malaysia',
      startDate: 'January 2021',
      endDate: 'September 2025',
      sort: 4,
      bullets: [
        { text: 'Remote and on-site support for individuals and SMBs.' },
        { text: 'Windows, Linux, malware, hardware, performance issues.' },
        { text: 'OS deployment, data migration, network troubleshooting.' },
        { text: 'End-to-end diagnosis and resolution.' },
      ],
      techTags: [
        { tag: 'Windows' },
        { tag: 'Linux' },
        { tag: 'Hardware support' },
        { tag: 'Networking' },
      ],
    },
  ],
  projects: [
    {
      title: 'Eventree',
      slug: 'eventree',
      projectType: 'build',
      projectUrl: 'https://eventree.online',
      summary: 'Penang events in one place — search, map, and calendar.',
      longDescription:
        "Events scatter across social media and posters. Eventree pulls them into one searchable map and calendar.\n\nLive at eventree.online.",
      technologies: [
        { name: 'React' },
        { name: 'Node.js' },
        { name: 'Maps' },
        { name: 'Calendar' },
        { name: 'Search' },
      ],
      featured: true,
      sort: 1,
    },
    {
      title: 'Internal Application Ecosystem',
      slug: 'internal-application-ecosystem',
      projectType: 'build',
      summary: 'Five internal apps — service desk, streaming, e-Stamping, and more.',
      longDescription:
        'Secure internal platforms for service management, media, and compliance — self-hosted on Docker and Dokploy.',
      technologies: [
        { name: 'React' },
        { name: 'Flask' },
        { name: 'Node.js' },
        { name: 'Docker' },
        { name: 'Cloudflare' },
        { name: 'GitHub Actions' },
        { name: 'Dokploy' },
      ],
      featured: true,
      sort: 2,
    },
    {
      title: 'Machine Monitoring Platform',
      slug: 'machine-monitoring-platform',
      projectType: 'build',
      summary: 'Real-time machine monitoring — Laravel, Python, MQTT at Schott Glass.',
      longDescription:
        'MQTT pipeline to collect, store, and display machine data. Deployed on Windows Server with IIS.',
      technologies: [
        { name: 'Laravel' },
        { name: 'Python' },
        { name: 'MQTT' },
        { name: 'MySQL' },
        { name: 'Windows Server' },
        { name: 'IIS' },
      ],
      featured: true,
      sort: 3,
    },
    {
      title: 'Kedai MASMED E-commerce Platform',
      slug: 'kedai-masmed-ecommerce',
      projectType: 'build',
      summary: 'Laravel e-commerce on cPanel — SSL, 8 domains, 99.5% uptime.',
      longDescription:
        'Full-stack Laravel store on cPanel with SSL, responsive design, and eight domains on shared hosting.',
      technologies: [
        { name: 'Laravel' },
        { name: 'MySQL' },
        { name: 'JavaScript' },
        { name: 'cPanel' },
        { name: 'SSL' },
      ],
      featured: true,
      sort: 4,
    },
    {
      title: 'Multi-Site Infrastructure Management',
      slug: 'multi-site-infrastructure',
      projectType: 'delivery',
      problem:
        'Five sites needed stable ICT and network ops — each with its own infrastructure and site lead.',
      solution:
        'Per-site network and ICT: switching, VLANs, wireless, CCTV, troubleshooting, vendor coordination, and security with site leads.',
      role: 'System Engineer / ICT service provider',
      outcome:
        'Reliable ops across five locations with documented assets. Zabbix live for web and office.',
      technologies: [
        { name: 'Fortinet' },
        { name: 'Cisco' },
        { name: 'HPE' },
        { name: 'Ubiquiti' },
        { name: 'VLAN' },
        { name: 'Zabbix' },
        { name: 'Microsoft 365' },
      ],
      architectureNotes:
        'Main office plus PDL Phase 1 & 2, Butterworth, and Batu Maung — each with local ICT ops and monitoring.',
      diagramType: 'multisite',
      featured: true,
      sort: 1,
    },
    {
      title: 'Digital Library Internet Migration',
      slug: 'digital-library-migration',
      projectType: 'delivery',
      problem: 'Upgrade library internet with minimal public disruption.',
      solution: 'Planned windows, tested failover, controlled cutover with verification.',
      role: 'System Engineer',
      outcome: '~15 minutes downtime. Connectivity verified post-migration.',
      technologies: [
        { name: 'Routing' },
        { name: 'Firewall' },
        { name: 'ISP coordination' },
        { name: 'Network testing' },
      ],
      architectureNotes: 'Controlled cutover with pre-migration testing.',
      diagramType: 'none',
      featured: true,
      sort: 2,
    },
    {
      title: 'Zabbix Monitoring Deployment',
      slug: 'zabbix-monitoring-deployment',
      projectType: 'delivery',
      problem: 'No proactive monitoring — outages hit staff and visitors first.',
      solution: 'Zabbix for website and office health with early alerting. Libraries rolling out next.',
      role: 'System Engineer',
      outcome: 'Monitoring live for web and office. Library sites in progress.',
      technologies: [
        { name: 'Zabbix' },
        { name: 'SNMP' },
        { name: 'Website monitoring' },
        { name: 'Linux' },
      ],
      architectureNotes: 'Zabbix on web and office today. Library coverage expanding.',
      diagramType: 'zabbix',
      featured: true,
      sort: 3,
    },
    {
      title: 'Self-Hosted DevOps Platform',
      slug: 'self-hosted-devops-platform',
      projectType: 'delivery',
      problem: 'Apps needed a reliable path from code to production without external-only hosting.',
      solution: 'GitHub Actions runners, Docker builds, Dokploy deploys, Cloudflare Tunnel and analytics.',
      role: 'System Engineer / DevOps',
      outcome: 'Consistent CI/CD to staging and production with secure access.',
      technologies: [
        { name: 'GitHub Actions' },
        { name: 'Docker' },
        { name: 'Dokploy' },
        { name: 'Cloudflare Tunnel' },
        { name: 'Cloudflare Analytics' },
        { name: 'VPS' },
      ],
      architectureNotes: 'GitHub → runner → Docker → Dokploy staging → production.',
      diagramType: 'devops',
      featured: true,
      sort: 4,
    },
    {
      title: 'Zakat Pulau Pinang Network Infrastructure Upgrade',
      slug: 'zakat-network-upgrade',
      projectType: 'delivery',
      problem: 'Four offices needed modernised network, security, and structured cabling.',
      solution: 'End-to-end PM: vendor coordination, hardware, cabling, zero-downtime migration.',
      role: 'Project Manager',
      outcome: 'Four offices upgraded on RM 150k+ budget — two weeks ahead of schedule.',
      technologies: [
        { name: 'Project management' },
        { name: 'Structured cabling' },
        { name: 'Network hardware' },
        { name: 'Security protocols' },
        { name: 'Vendor coordination' },
      ],
      architectureNotes: 'Multi-office modernisation with vendors, IT, and stakeholders.',
      diagramType: 'none',
      featured: true,
      sort: 5,
    },
  ],
  education: [
    {
      institution: 'Universiti Teknologi MARA (UiTM), Cawangan Perlis',
      degree: 'Bachelor of Computer Science (Hons.) — Netcentric Computing',
      dates: '2023 – 2026',
      highlights: [
        { text: 'CGPA: 3.50' },
        { text: "Dean's List: Semester 5, 6" },
      ],
      sort: 1,
    },
    {
      institution: 'Universiti Teknologi MARA (UiTM), Cawangan Perlis',
      degree: 'Diploma in Computer Science',
      dates: 'Completed 2023',
      highlights: [
        { text: 'CGPA: 3.39' },
        { text: "Dean's List: Semester 2" },
      ],
      sort: 2,
    },
  ],
  certifications: [
    { title: 'Ruijie Certified Network Associate – WLAN', category: 'networking', sort: 1 },
    { title: 'Netgear Certified Engineer', category: 'networking', sort: 2 },
    { title: 'Cisco networking training', category: 'networking', sort: 3 },
    { title: 'ExtremeCloud IQ Associate', category: 'networking', sort: 4 },
    { title: 'Fortinet NSE 1–3', category: 'cybersecurity', sort: 5 },
    { title: 'Google Cybersecurity Professional Certificate', category: 'cybersecurity', sort: 6 },
    { title: 'Dante Level 1', category: 'av', sort: 7 },
    { title: 'Dante Level 2', category: 'av', sort: 8 },
    { title: 'Dante AV', category: 'av', sort: 9 },
    { title: 'Hikvision Professional CCTV', category: 'av', sort: 10 },
  ],
}
